/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gacrnd_gcs_binder_MainActivity */

#ifndef _Included_com_gacrnd_gcs_binder_MainActivity
#define _Included_com_gacrnd_gcs_binder_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gacrnd_gcs_binder_MainActivity
 * Method:    writeTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gacrnd_gcs_binder_MainActivity_writeTest
  (JNIEnv *, jobject);

/*
 * Class:     com_gacrnd_gcs_binder_MainActivity
 * Method:    readTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gacrnd_gcs_binder_MainActivity_readTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
